version: '3'
services:
  db:
      image: mysql
      ports:
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: blog
          MYSQL_USER: sheldon
          MYSQL_PASSWORD: sheldon
  php:
      build: ./php-fpm
      ports:
        - 9000:9000
      volumes:
        - ./be-boilerplate:/var/www:rw
      links:
        - db
  nginx:
      build: ./nginx
      ports:
        - 80:80
      volumes:
        - ./logs/nginx:/etc/logs/nginx
      links:
        - php
