version: '3'
services:
  db:
      image: mysql
      ports:
          - 3306:3306
      volumes:
        - ./dump-db:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: blog
          MYSQL_USER: sheldon
          MYSQL_PASSWORD: root
#  test-db:
#      image: mysql
#      ports:
#          - 8080:3306
#      environment:
#          MYSQL_DATABASE: test_db
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_USER: test
#          MYSQL_PASSWORD: root
  php:
      build: ./php-fpm
      volumes:
        - ./be-boilerplate:/var/www:rw
      links:
        - db
#        - test-db
      environment:
        - XDEBUG_CONFIG=remote_host=192.168.0.12
  nginx:
      build: ./nginx
      ports:
        - 8082:8082
      volumes:
        - ./logs/nginx:/etc/logs/nginx
      links:
        - php
  jenkins:
      image: jenkinsci/blueocean
      ports:
          - 8080:8080
          - 49000:8080
      volumes:
        - ./jenkins-data:/var/jenkins_home
#  test-server:
#      build: ./nginx-test
#      ports:
#        - 81:81
#      volumes:
#        - ./logs/nginx:/etc/logs/nginx
#      links:
#        - php