#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation

get_posts:
    type: rest
    resource: App\Controller\BlogController
get_post:
    type: rest
    resource: App\Controller\BlogController