# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    database_host:     db
    database_port:     3306
    database_name:     blog
    database_user:     sheldon
    database_password: root
    database_charset:  UTF8
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in App/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../App/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../App/{Entity,Migrations,Repository,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../App/Controller'
        tags: ['controller.service_arguments']
    # makes classes in Domain/ available to be used as services
    Domain\:
        resource: '../Domain/*'
    # makes classes in Infrastructure/ available to be used as services
    Infrastructure\:
        resource: '../Infrastructure/*'
    # listening different type of exceptions
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

fos_rest:
    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false                           # We do not include format in request, so that all responses
    view:
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/vnd.api+json']
        force_redirects:
            html: true
        templating_formats:
            json: false
            xml: false
            html: false
        view_response_listener: force