FORMAT: 1A

# Backend boilerplate API

Simple backend skeleton - REST API project with JSON  serialization.

# Blog related calls

For retrieving posts, creating/updating and deleting calls

## Restaurant info [/posts]

### Retrieve restaurant delivery postcodes and localities [GET]
    + Headers

        Content-Type: application/json
        Origin: http://myblog.local

+ Request (application/json)

+ Response 200 (application/json)

    + Body

            {
                "hello":"world"
            }

