FORMAT: 1A

# Backend boilerplate API

Simple backend skeleton - REST API project with JSON  serialization.

# Blog related calls

## Post info [/posts/{id}]
+ Parameters
    + id: 1 (required, number) Post id

### Retrieve  [GET]
    + Headers

        Content-Type: application/json
        Origin: http://myblog.local

+ Request (application/json)

+ Response 200 (application/json)

    + Body

            {
                "id": "1",
                "title": "test",
                "description": "test desc",
                "created": "2017-10-29 19:26:42",
                "modified": "2017-10-29 19:26:45"
            }

