doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host:     '%env(DB_HOST)%'
                port:     '%env(DB_PORT)%'
                dbname:   '%env(DB_DATABASE)%'
                user:     '%env(DB_USERNAME)%'
                password: '%env(DB_PASSWORD)%'
                charset:  'UTF8'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore

